version: '3.7'
services: 
  ui:
    build: ./ui
    image: ${USERNAME}/ui:1.0
    ports:
      - ${COMMENT_SERVICE_PORT}:${COMMENT_SERVICE_PORT}/tcp
    networks:
      - front_net     
  comment:
    build: ./comment
    image: ${USERNAME}/comment:1.0
    networks:
      - front_net
      - back_net 
  post:
    build: ./post-py
    image: ${USERNAME}/post:1.0
    networks:
      - front_net
      - back_net 
  post_db:
    image: mongo:latest
    volumes:
      - reddit_db:/data/db
    networks:
      - back_net 
volumes:
  reddit_db:
    external: true
networks:
  front_net:
    name: front_net
    driver: bridge
    ipam:
      config:
        -
          subnet: 10.0.1.0/24
  back_net:
    name: back_net
    driver: bridge
    ipam:
      config:
        - 
          subnet: 10.0.2.0/24